spring.application.name=deal

server.port=8081

springdoc.swagger-ui.path=/

spring.datasource.url=jdbc:postgresql://localhost:5432/deal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
