spring.datasource.url=jdbc:postgresql://localhost:5432/deal
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.cloud.openfeign.client.config.deal-client.url=http://localhost:8080