spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.cloud.openfeign.client.config.deal-client.url=${CALCULATOR_LOCATION}

spring.kafka.bootstrap-servers=${BROKER_LOCATION}

app.finish-registration.url=${FINISH_REGISTRATION}
app.create-documents.url=${CREATE_DOCUMENTS}
app.send-code.url=${SEND_CODE}