spring.datasource.url=jdbc:postgresql://localhost:5432/deal
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.cloud.openfeign.client.config.deal-client.url=http://localhost:8080

spring.kafka.bootstrap-servers=localhost:9092

app.finish-registration.url=http://localhost:8081/swagger-ui/index.html#/deal-controller-impl/calculateCredit
app.create-documents.url=http://localhost:8081/swagger-ui/index.html#/deal-controller-impl/sendDocuments
app.send-code.url=http://localhost:8081/swagger-ui/index.html#/deal-controller-impl/sendCode