services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: deal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network

  broker:
    image: apache/kafka:4.1.0-rc0
    container_name: broker
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: 'finish-registration:1:1,create-documents:1:1,send-documents:1:1,send-ses:1:1,credit-issued:1:1,statement-denied:1:1'
    networks:
      - microservices-network

  calculator:
    build:
      context: ./calculator
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  deal:
    build:
      context: ./deal
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://postgres:5432/deal
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - CALCULATOR_LOCATION=http://calculator:8080
      - BROKER_LOCATION=broker:9092
      - FINISH_REGISTRATION=http://localhost:8084/swagger-ui/index.html#/deal-gateway-controller-impl/finishRegistration
      - CREATE_DOCUMENTS=http://localhost:8084/swagger-ui/index.html#/deal-gateway-controller-impl/createDocuments
      - SEND_CODE=http://localhost:8084/swagger-ui/index.html#/deal-gateway-controller-impl/signDocuments
    depends_on:
      - postgres
    networks:
      - microservices-network

  statement:
    build:
      context: ./statement
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DEAL_LOCATION=http://deal:8081
    networks:
      - microservices-network

  dossier:
    build:
      context: ./dossier
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - BROKER_LOCATION=broker:9092
      - SIGN_DOCUMENTS=http://localhost:8084/swagger-ui/index.html#/deal-gateway-controller-impl/verifySesCode
      - USERNAME=insert-your-mail
      - PASSWORD=insert-your-password
    depends_on:
      - broker
    networks:
      - microservices-network

  api-gateway:
    build:
      context: ./apigateway
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - STATEMENT_LOCATION=http://statement:8082
      - DEAL_LOCATION=http://deal:8081
    networks:
      - microservices-network

volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge