spring.kafka.bootstrap-servers=localhost:9092

spring.mail.username=username
spring.mail.password=password

app.sign-documents.url=http://localhost:8081/swagger-ui/index.html#/deal-controller-impl/signDocuments